# --- Required options --- #

title: Aaron Graifman
description: "Data Analyst | Program Evaluation Graduate Student"
author: Aaron Graifman

# --- Navigation --- #

navbar-links:
  Home: ""
  Academic Projects: "academic-projects"
  Tools: "tools"
  About: "aboutme"
  CV: "https://aaron13g.github.io/cv/"

# --- Logo (disable for now) --- #

# Remove avatar for clean look
# avatar: "/assets/img/g-logo-vice.png"
# round-avatar: true

# --- Footer Social Links --- #

social-network-links:
  email: "aaronmgraifman@gmail.com"
  github: aaron13g
  linkedin: aaron-graifman

# Disable RSS description (no blog yet)
# rss-description:

# --- General Options --- #

share-links-active:
  twitter: false
  facebook: false
  linkedin: false
  vk: false

post_search: false

# --- Colours --- #

# Primary accent (Plum)
navbar-col: "#4B1E3A"
navbar-text-col: "#FFFFFF"
navbar-children-col: "#F7F2F5"
navbar-border-col: "#3A162D"

# Page
page-col: "#FFFFFF"
text-col: "#2A2A2A"

# Links (Plum only)
link-col: "#4B1E3A"
hover-col: "#6A2A53"

# Footer (Neutral)
footer-col: "#F4F4F6"
footer-text-col: "#444444"
footer-link-col: "#4B1E3A"

collections:
  academic_projects:
    output: true
    permalink: /academic-projects/:name/

# --- You don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "America/Toronto"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 0

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false
      social-share: false
  -
    scope:
      path: "" # any file that's not a post will be a "page" layout by default
    values:
      layout: "page"


# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-sitemap
site-css:
  - /assets/css/custom.css


# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189

